main: fr.skyserver.adminplugin.AdminPlugin
name: AdminPlugin
version: 1.0
api-version: 1.20
author: tetemh
depend:
  - CorePlugin
commands:
  admin:
    description: Admin Command
    permission: adminplugin.adminpanel